export enum actionTypes {
  REQUEST_CREATE_POST = 'posts/REQUEST_CREATE_POST',
  REQUEST_LATEST_POSTS = 'posts/REQUEST_LATEST_POSTS',
  SET_ERROR_REQUEST_POST = 'posts/SET_ERROR_REQUEST_POST',
  SET_LATEST_POSTS = 'posts/SET_LATEST_POSTS',
  SET_POST = 'posts/SET_POST',
  SET_LOADED_POSTS = 'posts/SET_LOADED_POSTS',
}
